checkpoint

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -1,6 +1,6 @@
 #!/bin/bash
 printf 'running test suite at %s\n\n' "$(date)"
-start=$(date +"%s")
+start=$(date +"%s.%N")
 
 TESTDIR=$(pwd)/tests
 XR0=$(pwd)/bin/0v
@@ -19,46 +19,9 @@ fail="\e[31mFAIL\e[0m\n"
 pass="\e[32mPASS\e[0m\n"
 ignore="\e[33mIGNORE\e[0m\n"
 
-nignore=$(cat $IGNORE_FILE | wc -l)
-ignore_files=$(cat $IGNORE_FILE)
-
-for f in $ignore_files; do
-	file=$TESTDIR/0v/$f
-	if [ ! -f "$file" ]; then
-		printf "error: ignored file %s not found\n" "$file" 1>&2
-		exit
-	fi
-done
-
-should_ignore() {
-    for name in $ignore_files; do
-        if [ "$name" = "$1" ]; then
-            return 0
-        fi
-    done
-    return 1
-}
-
-cd $TESTDIR/0v
-
-ntests=$(ls */*.x | wc -l)
-
-length=$(ls */*.x | awk '{ print length, $0 }' | sort -n -s | cut -d' ' -f2- |
-	tail -1 | wc -c)
-
-# loop through and run tests
-for f in */*.x
-do
-	folder=$(dirname "$f")
-
-	printf "%-${length}s ..." "$f"
-	tempfile=$(mktemp)
-
-	# skip ignores
-	if should_ignore $f; then
-		printf "$ignore"
-		continue
-	fi
+run_test() {
+	folder=$1
+	tempfile=$2
 
 	if [ "$folder" == *"$topological_folder"* ]
 	then
@@ -81,27 +44,74 @@ do
 		echo "$output_file" | diff - $expected_file
 		if diff -q "$tempfile" "$expected_file" >/dev/null;
 		then
-			npass=$((npass+1))
-			printf "$pass"
+			return 0
 		else
-			printf "$fail"
+			return 1
 		fi
 	else
 		# silence is golden
 		if [[ $(cat $tempfile) -eq 0 ]] 
 		then
-			npass=$((npass+1))
-			printf "$pass"
+			return 0
 		fi
 	fi
+}
 
+nignore=$(cat $IGNORE_FILE | wc -l)
+ignore_files=$(cat $IGNORE_FILE)
+
+for f in $ignore_files; do
+	file=$TESTDIR/0v/$f
+	if [ ! -f "$file" ]; then
+		printf "error: ignored file %s not found\n" "$file" 1>&2
+		exit 1
+	fi
+done
+
+should_ignore() {
+    for name in $ignore_files; do
+        if [ "$name" = "$1" ]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+cd $TESTDIR/0v
+
+ntests=$(ls */*.x | wc -l)
+
+length=$(ls */*.x | awk '{ print length, $0 }' | sort -n -s | cut -d' ' -f2- |
+	tail -1 | wc -c)
+
+# loop through and run tests
+for f in */*.x
+do
+	printf "%-${length}s ..." "$f"
+
+	# skip ignores
+	if should_ignore $f; then
+		printf "$ignore"
+		continue
+	fi
+
+	tempfile=$(mktemp)
+	succ=$(run_test $(dirname "$f") $tempfile)
+	if [[ $succ -eq 0 ]]; then
+		npass=$((npass+1))
+		printf "$pass"
+	else
+		printf "$fail"
+	fi
 	rm $tempfile
+
 done
 
 nfail=$((ntests-(npass+nignore)))
-finish=$(date +"%s")
-printf '\n%d tests:\t%d passed\t%d failed\t%d ignored\tin %d seconds\n' \
-	$ntests $npass $nfail $nignore $((finish-start))
+finish=$(date +"%s.%N")
+time=$(echo "$finish-$start" | bc)
+printf "\n%d tests:\t%d passed\t%d failed\t%d ignored\tin %.3f seconds\n" \
+	$ntests $npass $nfail $nignore $time
 if [ $nfail -ne 0 ]
 then
 	exit 1
